# Generated by Django 5.2.13 on 2026-04-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_tel',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='pillar',
            field=models.CharField(blank=True, choices=[('MNS', 'Managed Network Services'), ('CYBERSECURITY', 'Cybersecurity'), ('IOT', 'IoT'), ('CLOUD', 'Cloud'), ('PLTE', 'PLTE')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ONGOING', 'Ongoing'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
    ]
