# Generated by Django 5.1.4 on 2026-05-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pillar_project_custom_fields_alter_project_pillar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contact_person',
            new_name='project_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget_spent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget_total',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contact_tel',
        ),
        migrations.AddField(
            model_name='project',
            name='tcv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Contract Value (RM)', max_digits=15, null=True),
        ),
    ]
