# Generated by Django 5.2.13 on 2026-04-09 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('DEADLINE_REMINDER', 'Deadline Reminder'), ('PROJECT_EXPIRED', 'Project Expired'), ('STATUS_CHANGED', 'Status Changed'), ('TASK_ASSIGNED', 'Task Assigned'), ('COMMENT_MENTION', 'Comment Mention'), ('BUDGET_ALERT', 'Budget Alert'), ('MILESTONE_DUE', 'Milestone Due'), ('DAILY_DIGEST', 'Daily Digest'), ('MEMBER_ADDED', 'Member Added'), ('FILE_SHARED', 'File Shared'), ('APPROVAL_REQUIRED', 'Approval Required'), ('TASK_COMPLETED', 'Task Completed'), ('OVERDUE_TASK', 'Overdue Task'), ('PROJECT_COMPLETED', 'Project Completed')], max_length=30)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('BEFORE_DEADLINE', 'Before Deadline'), ('SPECIFIC_DATE', 'Specific Date'), ('RECURRING', 'Recurring')], default='BEFORE_DEADLINE', max_length=20)),
                ('days_before', models.IntegerField(default=7)),
                ('remind_on', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In App'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='projects.project')),
                ('recipients', models.ManyToManyField(blank=True, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
