# Generated by Django 5.2.13 on 2026-04-13 07:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('projects', '0003_pillar_project_custom_fields_alter_project_pillar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.office365.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_user', models.EmailField(blank=True, default='', max_length=254)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.EmailField(default='noreply@projecttracker.local', max_length=254)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='ProjectExpiryReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.IntegerField(choices=[(4, '4 months before'), (3, '3 months before'), (2, '2 months before'), (1, '1 month before')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_json', models.JSONField(default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_reminders', to='projects.project')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('project', 'stage')},
            },
        ),
    ]
