# Generated by Django 5.2.13 on 2026-04-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailconfig_projectexpiryreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='display_name',
            field=models.CharField(blank=True, default='ProTracker Notifications', max_length=100),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='reply_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
