# Generated by Django 5.2.13 on 2026-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_whatsappconfig_whatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', help_text='Bot token from @BotFather, e.g. 123456:ABCdef...', max_length=255)),
                ('bot_username', models.CharField(blank=True, default='', help_text='Bot username without @, e.g. ProTrackerBot', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Configuration',
            },
        ),
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_chat_id', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('message_id', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WhatsAppConfig',
        ),
        migrations.DeleteModel(
            name='WhatsAppLog',
        ),
    ]
