# Generated by Django 5.2.13 on 2026-04-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pillar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES_MANAGER', 'Sales Manager'), ('PRESALES', 'Presales'), ('ACCOUNT_MANAGER', 'Account Manager')], default='ACCOUNT_MANAGER', max_length=20),
        ),
    ]
