# Generated by Django 5.2.13 on 2026-04-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_pillar_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('access_level', models.CharField(choices=[('ADMIN', 'Admin – Full platform management'), ('FULL_ACCESS', 'Full Access – All projects'), ('PILLAR_BASED', 'Pillar Based – Projects by assigned pillar'), ('OWN_ONLY', 'Own Only – Own projects only')], default='OWN_ONLY', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='ACCOUNT_MANAGER', max_length=100),
        ),
    ]
