# Generated by Django 5.2.13 on 2026-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='Telegram chat ID – set automatically when user sends /link to the bot', max_length=50),
        ),
    ]
