# Generated by Django 5.2.13 on 2026-04-09 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('size', models.CharField(default='medium', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('progress_percent', models.IntegerField(default=0)),
                ('tasks_total', models.IntegerField(default=0)),
                ('tasks_done', models.IntegerField(default=0)),
                ('tasks_overdue', models.IntegerField(default=0)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('logged_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
